export class Product {
  constructor(
    public toy_id: number,
    public toy_name: string,
    public gender: string,
    public age: string,
    public price: number,
    public avaliability: boolean,
    public brand: string
  ) {}
}
export const allProduct: Product[] = [
  {
    toy_id: 2,
    toy_name: '43 Piece dinner Set',
    gender: 'Female',
    age: '3 to 5',
    price: 12.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 1,
    toy_name: 'Balance Training Bicycle',
    gender: 'Neutral',
    age: '3 to 5',
    price: 119.95,
    avaliability: true,
    brand: 'SportsFun',
  },
  {
    toy_id: 7,
    toy_name: 'Best Friends Forever Magnetic Dress Up',
    gender: 'Female',
    age: '3 to 5',
    price: 24.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 8,
    toy_name: 'City Gargage Truck Lego',
    gender: 'Neutral',
    age: '3 to 5',
    price: 19.95,
    avaliability: false,
    brand: 'Lego',
  },
  {
    toy_id: 20,
    toy_name: 'Creator Beach House Lego',
    gender: 'Neutral',
    age: '6 to 8',
    price: 39.95,
    avaliability: false,
    brand: 'Lego',
  },
  {
    toy_id: 23,
    toy_name: 'Dancing Alligator',
    gender: 'Neutral',
    age: 'Baby',
    price: 19.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 11,
    toy_name: 'Earth DVD Game',
    gender: 'Neutral',
    age: 'over8',
    price: 34.99,
    avaliability: true,
    brand: 'VideoVroom',
  },
  {
    toy_id: 30,
    toy_name: 'Fisher-Price stroller',
    gender: 'Female',
    age: 'Toddler',
    price: 25.99,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 19,
    toy_name: 'Gourmet Cupcake Maker',
    gender: 'Female',
    age: '6 to 8',
    price: 39.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 4,
    toy_name: 'Hoppity Ball 26 inch',
    gender: 'Neutral',
    age: '3 to 5',
    price: 29.95,
    avaliability: true,
    brand: 'SportsFun',
  },
  {
    toy_id: 3,
    toy_name: 'Horses and Unicorns Set',
    gender: 'Neutral',
    age: '3 to 5',
    price: 24.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 21,
    toy_name: 'Jacques the Peacock Play and Grow',
    gender: 'Neutral',
    age: 'Toddler',
    price: 12.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 9,
    toy_name: 'Kettrike Tricycle',
    gender: 'Neutral',
    age: '3 to 5',
    price: 249.95,
    avaliability: false,
    brand: 'SportsFun',
  },
  {
    toy_id: 26,
    toy_name: 'Les Dollie Toffee Apple',
    gender: 'Female',
    age: 'Toddler',
    price: 24.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 24,
    toy_name: 'Mashaka the Monkey',
    gender: 'Neutral',
    age: 'Baby',
    price: 36.95,
    avaliability: true,
    brand: 'BarnyardBlast',
  },
  {
    toy_id: 28,
    toy_name: 'Melody Express Musical Train',
    gender: 'Male',
    age: 'Toddler',
    price: 42.95,
    avaliability: true,
    brand: 'Modelz',
  },
  {
    toy_id: 31,
    toy_name: 'Mortimer the Moose Play and Grow',
    gender: 'Neutral',
    age: 'Toddler',
    price: 12.95,
    avaliability: true,
    brand: 'CoolKidz',
  },

  {
    toy_id: 29,
    toy_name: 'My First LEGO DUPLO Set',
    gender: '',
    age: 'Toddler',
    price: 19.95,
    avaliability: true,
    brand: 'Lego',
  },
  {
    toy_id: 22,
    toy_name: 'Nutbrown Hare',
    gender: 'Neutral',
    age: 'Baby',
    price: 12.99,
    avaliability: false,
    brand: 'CoolKidz',
  },
  {
    toy_id: 14,
    toy_name: 'OMG - Gossip Girl Board Game',
    gender: 'Female',
    age: 'over8',
    price: 24.95,
    avaliability: true,
    brand: 'GeekToys',
  },
  {
    toy_id: 6,
    toy_name: 'Princess Palace',
    gender: 'Female',
    age: '3 to 5',
    price: 24.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
  {
    toy_id: 10,
    toy_name: 'Princess Training Bicycle',
    gender: 'Female',
    age: '3 to 5',
    price: 119.95,
    avaliability: false,
    brand: 'SportsFun',
  },
  {
    toy_id: 12,
    toy_name: 'Twilight Board Game',
    gender: 'Neutral',
    age: 'over8',
    price: 24.95,
    avaliability: true,
    brand: 'GeekToys',
  },
  {
    toy_id: 17,
    toy_name: 'Star Wars Darth Vader Lego',
    gender: 'Male',
    age: '6_to_8',
    price: 39.95,
    avaliability: true,
    brand: 'GeekToys',
  },
  {
    toy_id: 18,
    toy_name: 'Snoopy Sno-Cone Machine',
    gender: 'Neutral',
    age: '6_to_8',
    price: 24.95,
    avaliability: true,
    brand: 'Modelz',
  },
  {
    toy_id: 5,
    toy_name: 'Sleeping Queens Board Game',
    gender: 'Female',
    age: '3_to_5',
    price: 12.95,
    avaliability: false,
    brand: 'CoolKidz',
  },
  {
    toy_id: 25,
    toy_name: 'Sleep Sheep',
    gender: 'Neutral',
    age: 'Baby',
    price: 39.0,
    avaliability: true,
    brand: 'BarnyardBlast',
  },
  {
    toy_id: 13,
    toy_name: 'Settlers of Catan Board Game',
    gender: 'Neutral',
    age: 'over8',
    price: 44.95,
    avaliability: true,
    brand: 'GeekToys',
  },
  {
    toy_id: 16,
    toy_name: 'Scrabble',
    gender: 'Neutral',
    age: 'over8',
    price: 19.95,
    avaliability: true,
    brand: 'GeekToys',
  },
  {
    toy_id: 27,
    toy_name: 'Sand Play Set',
    gender: 'Neutral',
    age: 'Toddler',
    price: 24.95,
    avaliability: true,
    brand: 'Modelz',
  },
  {
    toy_id: 15,
    toy_name: 'Sailboat',
    gender: 'Male',
    age: 'over8',
    price: 24.95,
    avaliability: true,
    brand: 'CoolKidz',
  },
];
